travis:
  secure:
    BINSTAR_TOKEN: EyHDQ4HhfUqgAMr1Ahls9/sKOrCdbtqlZ+QaMwvz3374Op4vywVp8Yrsn4y7F1S5RQp2+Pl2UE+14cITod1fCBS9FFln3VY681LaYLW8DuuKTixi1eerjpY/S/xCmxai7+qhA23J7aU4r3NLrA5dFYOjzUAg1zyBjs9t0DjfaonmxwH0qhC5bt/qgi0nUWaXQDhi5fyRv3+BZ/yiCJMiXv4lzWndAWTQrUB4iwrpc4RvesB8fmHD631P32wGnXNxhd6W3XXLFiQeIYEzTH3+0B1pXGtwzl8v8fK0fF4XAfvH8wsQQ2m+nUmvNW86w25anYccyAnSFMo4tnoDILakVhrYM/a21ewbYpNd2ewh+Z/roQZ0c/sSpmFIPPdXXtyyCJCKKZxDYNxLEjk93rY71N1/ZOpsmkMVkdFGcayiQA8b5b47suRwAKpoFF5SZUl8fHxO8lgmlJtHReFbTZU5ne3itfGKbrATMlrs3kQoE0zR02Qp3WnGxBq0qvAZJPC/mZtBSn19KVnYVc0WQS5pgPEJBz+k6yIBK5394biNpjQ6AxPToZcLFV6V2u4ttvA+gxLlo/0rOiVJ6WMX/eCPxUyBDIx8t6Ry4O/AGTnrZz2vyBMFi8dngu+LeR8zdWQS+WUsVwO1wAj58XssS5NdX1v5B1Gt7qgnZuIoKnWSRvY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
